# Generated by Django 3.2.12 on 2022-03-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userGroups',
            field=models.CharField(choices=[('AD', '관리자'), ('NW', '네트워크부문'), ('EX', '임원'), ('USER', '직원')], default='USER', max_length=4, verbose_name='그룹'),
        ),
        migrations.AddField(
            model_name='user',
            name='userNickName',
            field=models.CharField(blank=True, max_length=10, verbose_name='이름'),
        ),
    ]
