# Generated by Django 3.2.12 on 2022-03-14 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220311_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userGroups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userNickName',
        ),
    ]
