# Generated by Django 3.2.12 on 2022-03-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20220314_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_me',
            field=models.BooleanField(default=False),
        ),
    ]
