# Generated by Django 3.2.12 on 2022-03-14 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_is_me'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_me',
        ),
    ]
